name: Workflow1

on:
  push:
    branches:
      - master

jobs:
  trigger:
    runs-on: self-hosted

    steps:
      - name: Workflow2
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_KEY }}
          repository: Dshirisha17/DEMO_PGM02C3


          
